#
# Makefile for generating HTML templates and code
#

COMMIT_HASH=$(shell git rev-parse --short HEAD)

MJML_TEMPLATES_DIR=templates/mjml
TYPESCRIPT_TEMPLATES_DIR=lib/templates/html

$(TYPESCRIPT_TEMPLATES_DIR)/%.ts: $(MJML_TEMPLATES_DIR)/%.mjml
	echo "// DO NOT EDIT THIS FILE" > $@
	echo "// this file was auto generated from '$<'" >> $@
	echo "export default function(" >> $@
	echo "  title: string," >> $@
	echo "  headlineText: string," >> $@
	echo "  senderOrganizationName: string," >> $@
	echo "  senderServiceName: string," >> $@
	echo "  titleText: string," >> $@
	echo "  contentHtml: string," >> $@
	echo "  footerHtml: string" >> $@
	echo "): string {" >> $@
	echo "  return \`" >> $@
	node_modules/.bin/mjml -m -s $< >> $@
	echo "\`;" >> $@
	echo "}" >> $@

mjml: $(TYPESCRIPT_TEMPLATES_DIR)/default.ts

all: mjml
