// tslint:disable:ordered-imports
// tslint:disable:no-consecutive-blank-lines
// tslint:disable:no-trailing-whitespace
// tslint:disable:max-line-length
// tslint:disable:jsdoc-format
// tslint:disable:interface-name
// tslint:disable:no-any

/**
 * The HTTP status code generated by the origin server for this occurrence
of the problem.

 */

import { Option } from "ts-option";

import {
  isWithinRangeNumber,
  toWithinRangeNumber,
  WithinRangeNumber
} from "../../utils/numbers";

export type HttpStatusCode = WithinRangeNumber<100, 600>;

export function isHttpStatusCode(arg: any): arg is HttpStatusCode {
  return isWithinRangeNumber(arg, 100, 600);
}

export function toHttpStatusCode(arg: any): Option<HttpStatusCode> {
  return toWithinRangeNumber(arg, 100, 600);
}
